// Map data references and country codes
export const WORLD_COUNTRIES = [
  { id: 'AFG', name: 'Afghanistan' },
  { id: 'ALB', name: 'Albania' },
  { id: 'DZA', name: 'Algeria' },
  { id: 'AND', name: 'Andorra' },
  { id: 'AGO', name: 'Angola' },
  { id: 'ARG', name: 'Argentina' },
  { id: 'ARM', name: 'Armenia' },
  { id: 'AUS', name: 'Australia' },
  { id: 'AUT', name: 'Austria' },
  { id: 'AZE', name: 'Azerbaijan' },
  { id: 'BHS', name: 'Bahamas' },
  { id: 'BHR', name: 'Bahrain' },
  { id: 'BGD', name: 'Bangladesh' },
  { id: 'BRB', name: 'Barbados' },
  { id: 'BLR', name: 'Belarus' },
  { id: 'BEL', name: 'Belgium' },
  { id: 'BLZ', name: 'Belize' },
  { id: 'BEN', name: 'Benin' },
  { id: 'BTN', name: 'Bhutan' },
  { id: 'BOL', name: 'Bolivia' },
  { id: 'BIH', name: 'Bosnia and Herzegovina' },
  { id: 'BWA', name: 'Botswana' },
  { id: 'BRA', name: 'Brazil' },
  { id: 'BRN', name: 'Brunei' },
  { id: 'BGR', name: 'Bulgaria' },
  { id: 'BFA', name: 'Burkina Faso' },
  { id: 'BDI', name: 'Burundi' },
  { id: 'KHM', name: 'Cambodia' },
  { id: 'CMR', name: 'Cameroon' },
  { id: 'CAN', name: 'Canada' },
  { id: 'CPV', name: 'Cape Verde' },
  { id: 'CAF', name: 'Central African Republic' },
  { id: 'TCD', name: 'Chad' },
  { id: 'CHL', name: 'Chile' },
  { id: 'CHN', name: 'China' },
  { id: 'COL', name: 'Colombia' },
  { id: 'COM', name: 'Comoros' },
  { id: 'COG', name: 'Congo' },
  { id: 'COD', name: 'Democratic Republic of Congo' },
  { id: 'CRI', name: 'Costa Rica' },
  { id: 'HRV', name: 'Croatia' },
  { id: 'CUB', name: 'Cuba' },
  { id: 'CYP', name: 'Cyprus' },
  { id: 'CZE', name: 'Czech Republic' },
  { id: 'DNK', name: 'Denmark' },
  { id: 'DJI', name: 'Djibouti' },
  { id: 'DOM', name: 'Dominican Republic' },
  { id: 'ECU', name: 'Ecuador' },
  { id: 'EGY', name: 'Egypt' },
  { id: 'SLV', name: 'El Salvador' },
  { id: 'GNQ', name: 'Equatorial Guinea' },
  { id: 'ERI', name: 'Eritrea' },
  { id: 'EST', name: 'Estonia' },
  { id: 'ETH', name: 'Ethiopia' },
  { id: 'FJI', name: 'Fiji' },
  { id: 'FIN', name: 'Finland' },
  { id: 'FRA', name: 'France' },
  { id: 'GAB', name: 'Gabon' },
  { id: 'GMB', name: 'Gambia' },
  { id: 'GEO', name: 'Georgia' },
  { id: 'DEU', name: 'Germany' },
  { id: 'GHA', name: 'Ghana' },
  { id: 'GRC', name: 'Greece' },
  { id: 'GRD', name: 'Grenada' },
  { id: 'GTM', name: 'Guatemala' },
  { id: 'GIN', name: 'Guinea' },
  { id: 'GNB', name: 'Guinea-Bissau' },
  { id: 'GUY', name: 'Guyana' },
  { id: 'HTI', name: 'Haiti' },
  { id: 'HND', name: 'Honduras' },
  { id: 'HUN', name: 'Hungary' },
  { id: 'ISL', name: 'Iceland' },
  { id: 'IND', name: 'India' },
  { id: 'IDN', name: 'Indonesia' },
  { id: 'IRN', name: 'Iran' },
  { id: 'IRQ', name: 'Iraq' },
  { id: 'IRL', name: 'Ireland' },
  { id: 'ISR', name: 'Israel' },
  { id: 'ITA', name: 'Italy' },
  { id: 'CIV', name: 'Ivory Coast' },
  { id: 'JAM', name: 'Jamaica' },
  { id: 'JPN', name: 'Japan' },
  { id: 'JOR', name: 'Jordan' },
  { id: 'KAZ', name: 'Kazakhstan' },
  { id: 'KEN', name: 'Kenya' },
  { id: 'KWT', name: 'Kuwait' },
  { id: 'KGZ', name: 'Kyrgyzstan' },
  { id: 'LAO', name: 'Laos' },
  { id: 'LVA', name: 'Latvia' },
  { id: 'LBN', name: 'Lebanon' },
  { id: 'LSO', name: 'Lesotho' },
  { id: 'LBR', name: 'Liberia' },
  { id: 'LBY', name: 'Libya' },
  { id: 'LIE', name: 'Liechtenstein' },
  { id: 'LTU', name: 'Lithuania' },
  { id: 'LUX', name: 'Luxembourg' },
  { id: 'MKD', name: 'North Macedonia' },
  { id: 'MDG', name: 'Madagascar' },
  { id: 'MWI', name: 'Malawi' },
  { id: 'MYS', name: 'Malaysia' },
  { id: 'MDV', name: 'Maldives' },
  { id: 'MLI', name: 'Mali' },
  { id: 'MLT', name: 'Malta' },
  { id: 'MRT', name: 'Mauritania' },
  { id: 'MUS', name: 'Mauritius' },
  { id: 'MEX', name: 'Mexico' },
  { id: 'MDA', name: 'Moldova' },
  { id: 'MCO', name: 'Monaco' },
  { id: 'MNG', name: 'Mongolia' },
  { id: 'MNE', name: 'Montenegro' },
  { id: 'MAR', name: 'Morocco' },
  { id: 'MOZ', name: 'Mozambique' },
  { id: 'MMR', name: 'Myanmar' },
  { id: 'NAM', name: 'Namibia' },
  { id: 'NPL', name: 'Nepal' },
  { id: 'NLD', name: 'Netherlands' },
  { id: 'NZL', name: 'New Zealand' },
  { id: 'NIC', name: 'Nicaragua' },
  { id: 'NER', name: 'Niger' },
  { id: 'NGA', name: 'Nigeria' },
  { id: 'PRK', name: 'North Korea' },
  { id: 'NOR', name: 'Norway' },
  { id: 'OMN', name: 'Oman' },
  { id: 'PAK', name: 'Pakistan' },
  { id: 'PSE', name: 'Palestine' },
  { id: 'PAN', name: 'Panama' },
  { id: 'PNG', name: 'Papua New Guinea' },
  { id: 'PRY', name: 'Paraguay' },
  { id: 'PER', name: 'Peru' },
  { id: 'PHL', name: 'Philippines' },
  { id: 'POL', name: 'Poland' },
  { id: 'PRT', name: 'Portugal' },
  { id: 'QAT', name: 'Qatar' },
  { id: 'ROU', name: 'Romania' },
  { id: 'RUS', name: 'Russia' },
  { id: 'RWA', name: 'Rwanda' },
  { id: 'SAU', name: 'Saudi Arabia' },
  { id: 'SEN', name: 'Senegal' },
  { id: 'SRB', name: 'Serbia' },
  { id: 'SYC', name: 'Seychelles' },
  { id: 'SLE', name: 'Sierra Leone' },
  { id: 'SGP', name: 'Singapore' },
  { id: 'SVK', name: 'Slovakia' },
  { id: 'SVN', name: 'Slovenia' },
  { id: 'SLB', name: 'Solomon Islands' },
  { id: 'SOM', name: 'Somalia' },
  { id: 'ZAF', name: 'South Africa' },
  { id: 'KOR', name: 'South Korea' },
  { id: 'SSD', name: 'South Sudan' },
  { id: 'ESP', name: 'Spain' },
  { id: 'LKA', name: 'Sri Lanka' },
  { id: 'SDN', name: 'Sudan' },
  { id: 'SUR', name: 'Suriname' },
  { id: 'SWZ', name: 'Eswatini' },
  { id: 'SWE', name: 'Sweden' },
  { id: 'CHE', name: 'Switzerland' },
  { id: 'SYR', name: 'Syria' },
  { id: 'TJK', name: 'Tajikistan' },
  { id: 'TZA', name: 'Tanzania' },
  { id: 'THA', name: 'Thailand' },
  { id: 'TLS', name: 'Timor-Leste' },
  { id: 'TGO', name: 'Togo' },
  { id: 'TON', name: 'Tonga' },
  { id: 'TTO', name: 'Trinidad and Tobago' },
  { id: 'TUN', name: 'Tunisia' },
  { id: 'TUR', name: 'Turkey' },
  { id: 'TKM', name: 'Turkmenistan' },
  { id: 'UGA', name: 'Uganda' },
  { id: 'UKR', name: 'Ukraine' },
  { id: 'ARE', name: 'United Arab Emirates' },
  { id: 'GBR', name: 'United Kingdom' },
  { id: 'USA', name: 'United States' },
  { id: 'URY', name: 'Uruguay' },
  { id: 'UZB', name: 'Uzbekistan' },
  { id: 'VUT', name: 'Vanuatu' },
  { id: 'VAT', name: 'Vatican City' },
  { id: 'VEN', name: 'Venezuela' },
  { id: 'VNM', name: 'Vietnam' },
  { id: 'YEM', name: 'Yemen' },
  { id: 'ZMB', name: 'Zambia' },
  { id: 'ZWE', name: 'Zimbabwe' },
];

export const US_STATES = [
  { id: '01', name: 'Alabama' },
  { id: '02', name: 'Alaska' },
  { id: '04', name: 'Arizona' },
  { id: '05', name: 'Arkansas' },
  { id: '06', name: 'California' },
  { id: '08', name: 'Colorado' },
  { id: '09', name: 'Connecticut' },
  { id: '10', name: 'Delaware' },
  { id: '11', name: 'District of Columbia' },
  { id: '12', name: 'Florida' },
  { id: '13', name: 'Georgia' },
  { id: '15', name: 'Hawaii' },
  { id: '16', name: 'Idaho' },
  { id: '17', name: 'Illinois' },
  { id: '18', name: 'Indiana' },
  { id: '19', name: 'Iowa' },
  { id: '20', name: 'Kansas' },
  { id: '21', name: 'Kentucky' },
  { id: '22', name: 'Louisiana' },
  { id: '23', name: 'Maine' },
  { id: '24', name: 'Maryland' },
  { id: '25', name: 'Massachusetts' },
  { id: '26', name: 'Michigan' },
  { id: '27', name: 'Minnesota' },
  { id: '28', name: 'Mississippi' },
  { id: '29', name: 'Missouri' },
  { id: '30', name: 'Montana' },
  { id: '31', name: 'Nebraska' },
  { id: '32', name: 'Nevada' },
  { id: '33', name: 'New Hampshire' },
  { id: '34', name: 'New Jersey' },
  { id: '35', name: 'New Mexico' },
  { id: '36', name: 'New York' },
  { id: '37', name: 'North Carolina' },
  { id: '38', name: 'North Dakota' },
  { id: '39', name: 'Ohio' },
  { id: '40', name: 'Oklahoma' },
  { id: '41', name: 'Oregon' },
  { id: '42', name: 'Pennsylvania' },
  { id: '44', name: 'Rhode Island' },
  { id: '45', name: 'South Carolina' },
  { id: '46', name: 'South Dakota' },
  { id: '47', name: 'Tennessee' },
  { id: '48', name: 'Texas' },
  { id: '49', name: 'Utah' },
  { id: '50', name: 'Vermont' },
  { id: '51', name: 'Virginia' },
  { id: '53', name: 'Washington' },
  { id: '54', name: 'West Virginia' },
  { id: '55', name: 'Wisconsin' },
  { id: '56', name: 'Wyoming' },
];

export const AU_STATES = [
  { id: 'NSW', name: 'New South Wales' },
  { id: 'VIC', name: 'Victoria' },
  { id: 'QLD', name: 'Queensland' },
  { id: 'SA', name: 'South Australia' },
  { id: 'WA', name: 'Western Australia' },
  { id: 'TAS', name: 'Tasmania' },
  { id: 'NT', name: 'Northern Territory' },
  { id: 'ACT', name: 'Australian Capital Territory' },
];
